#%RAML 1.0 DataType
displayName: Common Response Format
description: The common response format used for all API Calls.
properties:
  errorDescription:
    type: string
    description: A description of the error.
    example: Missing required header - x-api-correlation-id
    required: true
  errorType:
    type: string
    description: A unique code identifying the error.
    example: 'HTTP'
    required: true
  errorCode:
    type: string
    description: A unique code identifying the error.
    example: 'API_GET_001'
    required: true
  errorDateTime:
    type: string
    required: true
    description: A timestamp identifying the time of the error.
    example: "2020-01-01T00:00:01"
  additionalDetails:
    type: any
    required: false
    description: An optional attribute that could be of any type, usually an object or string that provides extra details around the exception cause.
    examples:
      simple-string:
        "HTTP Header x-correlation-id was provided but failed to be transmitted downstream."
